image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - https://download.zazukoians.org/expressive-rdf-mapper/expressive-rdf-mapper-1.2.0.vsix
    - https://Zazuko.gallery.vsassets.io/_apis/public/gallery/publisher/Zazuko/extension/vscode-rdf-sketch/0.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

tasks:
  - before: |
      wget https://download.visualstudio.microsoft.com/download/pr/022d9abf-35f0-4fd5-8d1c-86056df76e89/477f1ebb70f314054129a9f51e9ec8ec/dotnet-sdk-2.2.207-linux-x64.tar.gz
      mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-2.2.207-linux-x64.tar.gz -C $HOME/dotnet
      export DOTNET_ROOT=$HOME/dotnet
      export PATH=$PATH:$HOME/dotnet
      printf 'export PATH="%s:$PATH"\n' "/home/gitpod/.dotnet/tools" >> $HOME/.bashrc && exit
  - name: convert
    init: dotnet tool install -g r2rml4net-cli; yarn
    command: yarn transform
