image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - https://download.zazukoians.org/expressive-rdf-mapper/expressive-rdf-mapper-1.2.0.vsix
    - https://Zazuko.gallery.vsassets.io/_apis/public/gallery/publisher/Zazuko/extension/vscode-rdf-sketch/0.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

tasks:
  - before: |
      export DOTNET_ROOT=$HOME/dotnet
      export PATH=$PATH:$HOME/dotnet

  - name: convert
    init: yarn
    command: yarn start
